management:
  tracing:
    baggage:
      correlation:
        fields:
          - myBaggageFilter
          - myBaggageController
      remote-fields:
        - myBaggageFilter
        - myBaggageController
    sampling:
      probability: 1.0
    propagation:
      type: b3
logging:
  level:
    com.grassehh: debug
    org.zalando.logbook: trace
  pattern:
    console: "MDC Context: [%mdc] - %clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"